# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Sar/Downloads/Proyecto/Reloj_Digital.cache/wt [current_project]
set_property parent.project_path C:/Users/Sar/Downloads/Proyecto/Reloj_Digital.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Sar/Downloads/ef-reloj-digital-p5-final/contador_mod_60.vhd
  C:/Users/Sar/Downloads/ef-reloj-digital-p5-final/siete_segmentos_4bits_mux.vhd
  C:/Users/Sar/Downloads/ef-reloj-digital-p5-final/contador_mod_24.vhd
  C:/Users/Sar/Downloads/ef-reloj-digital-p5-final/siete_segmentos_4bits.vhd
  C:/Users/Sar/Downloads/ef-reloj-digital-p5-final/clk200Hz.vhd
  C:/Users/Sar/Downloads/ef-reloj-digital-p5-final/contador_reloj_automatico.vhd
  C:/Users/Sar/Downloads/ef-reloj-digital-p5-final/clk1Hz.vhd
  C:/Users/Sar/Downloads/ef-reloj-digital-p5-final/contador_reloj_manual.vhd
  C:/Users/Sar/Downloads/ef-reloj-digital-p5-final/clk2Hz.vhd
  C:/Users/Sar/Downloads/ef-reloj-digital-p5-final/siete_segmentos_4bits_completo.vhd
  C:/Users/Sar/Downloads/ef-reloj-digital-p5-final/clk4Hz.vhd
  C:/Users/Sar/Downloads/ef-reloj-digital-p5-final/reloj_digital.vhd
}
read_xdc C:/Users/Sar/Downloads/Proyecto/Reloj_Digital.srcs/constrs_1/new/Pines.xdc
set_property used_in_implementation false [get_files C:/Users/Sar/Downloads/Proyecto/Reloj_Digital.srcs/constrs_1/new/Pines.xdc]

catch { write_hwdef -file reloj_digital.hwdef }
synth_design -top reloj_digital -part xc7a100tcsg324-1
write_checkpoint -noxdef reloj_digital.dcp
catch { report_utilization -file reloj_digital_utilization_synth.rpt -pb reloj_digital_utilization_synth.pb }
