set_property PACKAGE_PIN J17 [get_ports {mux[3]}]
set_property PACKAGE_PIN J18 [get_ports {mux[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mux[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mux[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mux[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mux[0]}]
set_property PACKAGE_PIN H15 [get_ports {seg[7]}]
set_property PACKAGE_PIN T11 [get_ports {seg[5]}]
set_property PACKAGE_PIN P15 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN H17 [get_ports lucecita]
set_property IOSTANDARD LVCMOS33 [get_ports lucecita]
set_property PACKAGE_PIN J15 [get_ports ver_ms]
set_property IOSTANDARD LVCMOS33 [get_ports ver_ms]
set_property PACKAGE_PIN N14 [get_ports {edo_out[2]}]
set_property PACKAGE_PIN J13 [get_ports {edo_out[1]}]
set_property PACKAGE_PIN K15 [get_ports {edo_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {edo_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {edo_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {edo_out[0]}]
set_property PACKAGE_PIN M18 [get_ports increm]
set_property IOSTANDARD LVCMOS33 [get_ports increm]
set_property IOSTANDARD LVCMOS33 [get_ports selec]
set_property PACKAGE_PIN N17 [get_ports selec]
set_property PACKAGE_PIN P17 [get_ports areset]
set_property PACKAGE_PIN M17 [get_ports cancel]
set_property IOSTANDARD LVCMOS33 [get_ports areset]
set_property IOSTANDARD LVCMOS33 [get_ports cancel]


set_property PACKAGE_PIN L18 [get_ports {seg[6]}]


set_property PACKAGE_PIN K13 [get_ports {seg[3]}]
set_property PACKAGE_PIN K16 [get_ports {seg[2]}]
set_property PACKAGE_PIN R10 [get_ports {seg[1]}]
set_property PACKAGE_PIN T10 [get_ports {seg[0]}]
set_property PACKAGE_PIN T9 [get_ports {mux[1]}]
set_property PACKAGE_PIN J14 [get_ports {mux[0]}]
